title:              Makey's Social Data Science
email:              s213163@dtu.dk
description:        Welcome to my webpage build for the course Social Data Analysis and Visualization 02806, Technical University of Denmark. My name is Thomas Adamopoulos, I'm a MSc Transport % Logistics student, and I'm here to tell you some awesome stories based on data visualization.
author:             Thomas Adamopoulos
baseurl:            ""
url:                ""

# Social Profiles
twitter_username:   
github_username:      GitMakey
facebook_username:  
instagram_username:  
linkedin_profile:     https://www.linkedin.com/in/thomas-adamopoulos/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-youtube
  - jekyll-spaceship
  - jekyll-latex